spring:
  application:
    name: projectManagement
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/digix
    username: main
    password: password
